# Generated by Django 5.1.3 on 2024-11-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_accepted',
        ),
    ]
